# Generated by Django 5.2.8 on 2025-11-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10, unique=True)),
                ('airline', models.CharField(max_length=50)),
                ('departure_airport', models.CharField(max_length=50)),
                ('arrival_airport', models.CharField(max_length=50)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available_seats', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('on-time', 'On-time'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='on-time', max_length=10)),
                ('icao24', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'ordering': ['departure_time'],
                'indexes': [models.Index(fields=['departure_airport'], name='flights_fli_departu_2eab1f_idx'), models.Index(fields=['arrival_airport'], name='flights_fli_arrival_4e0efb_idx'), models.Index(fields=['departure_time'], name='flights_fli_departu_5bc2af_idx')],
            },
        ),
    ]
